README.md
=> Update README.md dfg

README.md
https://qwerty.atlassian.net/browse/ABC-1
=> Update README.md link test 2

README.md
=> Update README.md 25m

README.md
=> Update README.md [25m]

README.md
=> Update README.md times test 1

README.md
=> Update README.md times test 2 [20m]

README.md
=> Update README.md  times test 3 [30m]

README.md
=> Update README.md times test 4 [35m]

README.md
=> Update README.md  times test 6 [45m]

README.md
=> Update README.md [45m]

README.md
=> Update README.md no time unassigned PR Rev

README.md
http://neverssl.com/online/
213.108.54.200:8080/login
https://api.example.com/v1/users?username=johndoe&limit=10 https://www.example.com/products/item123?color=blue#details ftp://ftp.example.com/files/documents/
http://192.168.0.1/page
https://münchen.example/
https://blog.example.com/post/123
https://www.example.com:8080/path
https://www.example.com/search?q=url%20parsing&lang=en /page/about-us
=> Update README.md links/urls test 3

README.md
=> Update README.md some unique title sfijaof3

README.md
=> Update README.md [2h]

README.md
=> Update README.md no time

README.md
=> Update README.md saer

README.md
https://changecaptain.atlassian.net/browse/SEAL-617
=> Update README.md Jira link

README.md
not connected, Did not have connection before 2
=> Update README.mdnot connected, Did not have connection before 2

README.md
=> notimeUpdate README.md

README.md
=> Update README.mdmerge resolve 2

README.md
=> Update README.md#100 [1h 40m]

README.md
=> Update README.md#101 [1h 41m]

README.md
=> Update README.md unlinked

README.md
=> PR 127 [5m]

README.md
=> PR 143 [143h]

README.md
=> PR 150 [1h50m]

README.md
=> PR 151 [1h51m]

README.md
=> PR 152 [1h52m]

README.md
=> PR 154 [1h54m]

README.md
=> Unlinked - PR 159 [1h59m]

README.md
=> Unlinked - PR 160 [1h60m]

README.md
=> PR 165 [16h5m]

README.md
=>  PR 166 (PR #1 to the branch of the PR #165)

README.md
=> PR 168 - not tracked

README.md
=> PR 169 - not tracked

README.md
=> PR 171 - tracked [1m]

README.md
=> PR 173 [3m]

README.md
=> PR 175 [17h5m]

README.md
=> PR 176 [17h6m]

README.md
=> PR 183 [18h3m]

README.md
=> PR 184 [18h4m]

README.md
[x] Task
https://changecaptain.atlassian.net/browse/SEAL-720
=> PR 186 [18h6m]

README.md
[x] Bug
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-725
=> PR 188 [18h8m]

README.md
[x] Task
https://changecaptain.atlassian.net/browse/SEAL-725
=> PR 190 [19h]

README.md
=> PR 192 [19h2m]

README.md
[x] Feature
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-888
=> PR 193 [19h3m]

README.md
Post-Launch
[x] Feature
https://changecaptain.atlassian.net/browse/SEAL-888
=> PR 194 [19h4m]

README.md
[x] Bug
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-888
=> PR 195 [19h5m]

README.md
=> PR 197 [19h7m]

README.md
=> PR 198 [19h8m]

README.md
[x] Feature
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-919
=> PR 200 [20h]

README.md
[x] Feature
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-680
=> PR 202 [20h2m]

README.md
[x] Bug
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-680
=> PR 203 [20h3m]

README.md
=> PR 205 [20h5m]

README.md
=> PR 204 [20h4m]

README.md
=> PR 206 [20h6m]

README.md
[x] Bug
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-892
=> PR 208 [20h8m]

README.md
[x] Task
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-892
=> PR 209 [20h9m]

README.md
[x] Feature
https://changecaptain.atlassian.net/browse/SEAL-941
=> PR 210 [20h10m]

README.md
[x] Feature
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-923
=> PR 213 [20h13m]

README.md
=> PR 216 [20h16m]

README.md
=> PR 217 [20h17m]

README.md
=> PR 218 [20h18m]

README.md
=> PR 223 [2h23m]

README.md
=> PR 214 [20h14m]

README.md
=> PR 224 [2h24m]

README.md
=> PR 226 [2h26m]

README.md
=> PR 229 [2h29m]

README.md
=> PR 230 [2h30m]

README.md
=> PR 231 [2h31m]

README.md
=> PR 232 [2h32m]

README.md
[x] Bug
[x] Software
https://changecaptain.atlassian.net/browse/SEAL-2
=> PR 233 [2h33m]

README.md
developchangecaptain PR
[x] Feature
https://changecaptain.atlassian.net/browse/SEAL-1278
=> PR 301 Unlinkled developchangecaptain user

README.md
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1446
=> Desynced - PR 314

README.md
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1464
=> Unlinked anomaly - PR 318

README.md
- [] Feature
- [] Bug
- [] Task
=> Unlinked user - PR 323

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 324 - Missed commit time

README.md
- [] Feature
- [] Bug
- [] Task
=> PR - 346 - unlinked user anomaly

README.md
- [] Feature
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1604
=> PR 347 - Not tracked, left for auto-creation after getting up of the app

README.md
https://changecaptain.atlassian.net/browse/EWQ-11
=> PR 398 - missingTicket check

README.md
=> PR 428 - Missing ticket

README.md
=> PR 437 - removed unnecessary unlinked tag

README.md
=> PR 438 - removed unnecessary unlinked tag

README.md
=> PR 439 - no ext ticket

README.md
https://changecaptain.atlassian.net/browse/SEAL-1746
=> PR 443 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 510 - broken time logs and events

README.md
- [] Feature
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-3
=> PR 512 - broken time logs and events

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 516 - Unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 525 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-4
=> PR 535 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 537 - unlinked user

README.md
- [] Feature
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1323
=> PR 541 - unlinked user

README.md
- [] Feature
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1841
=> PR 547 - unlinked user

README.md
- [] Feature
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1843
=> PR 549 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1461
=> PR 551 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 558 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 560 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1442
=> PR 563 - out of sync

README.md
- [] Feature
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1841
=> PR 565 - unlinked user

README.md
=> PR 577 - Missed Ticket Type

README.md
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-2
=> PR 585 - "PR_OUT_OF_SYNC"

README.md
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-4
=> PR 586 - "PR_OUT_OF_SYNC"

README.md
- [] Feature
- [] Bug
https://changecaptain.atlassian.net/browse/SEAL-5
=> PR 591 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 593 - unlinked user becomes linked, PR_OUT_OF_SYNC

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 594 - PR_OUT_OF_SYNC

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 595 - PR_OUT_OF_SYNC

README.md
- [] Feature
- [] Bug
- [] Task
=> Not Tracked

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 600 - Unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 604 - PR_OUT_OF_SYNC

README.md
- [] Bug
- [] Task
https://unique.atlassian.net/browse/UNIQ-6
=> PR 605 - unlinked and PR_OUT_OF_SYNC

README.md
- [] Feature
- [] Bug
- [] Task
https://unique.atlassian.net/browse/UNIQ-6
=> PR 606 - PR_OUT_OF_SYNC, unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 635 - unlinked user

README.md
- [] Feature
- [] Task
https://changecaptain.atlassian.net/browse/PATCH-2
=> PROD PR 642

README.md
- [] Feature
- [] Bug
https://changecaptain.atlassian.net/browse/PATCH-2
=> PROD PR 641

README.md
- [] Feature
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-1568
=> Mailtesting244-patch-674566

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 703 main

README.md
=> PR 709 updt1

README.md
- [] Feature
- [] Task
https://qwe.atlassian.net/browse/ASD-7
=> PR 711 - upd ~`!@#$%^&*()_+=-}{][":';?></.,

README.md
- [] Bug
- [] Task
https://changecaptain.atlassian.net/browse/SEAL-2710
=> PR 776 - unlinked user

README.md
- [] Feature
- [] Bug
- [] Task
=> PR 783 - unlinked user
